version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=my_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '54320:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # mysql:
  #   image: mysql:5
  #   environment:
  #    - MYSQL_DATABASE=my_db
  #    - MYSQL_USER=root
  #    - MYSQL_PASSWORD=123456
  #    - MYSQL_ROOT_PASSWORD=123456
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_ARBITRARY=1
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mysql